name: Verify Build Workflow
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [main]
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [main]

jobs:
  build-verify:
    name: Verify Build
    runs-on: buntu-20.04
    if: github.repository_owner == 'Apicurio'
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Check Java Version
        run: java -version

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.4'

      - name: Check Maven Version
        run: mvn --version

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Project
        run: mvn clean install
